config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #CRUD
  #Create, Read, Update, Delete
  #Read all the task
  get '/tasks', to: 'tasks#index'
  #Read one task
  get '/tasks/new', to: 'tasks#new' #display the form
  get '/tasks/:id', to: 'tasks#show', as: 'show_task'
  #Create a task
  post '/tasks', to: 'tasks#create'
  #Update a task
  get '/tasks/:id/edit', to: 'tasks#edit', as: 'task'
  patch '/tasks/:id/edit', to: 'tasks#update'
  #Delete a task
  delete '/tasks/:id', to: 'tasks#destroy', as: 'destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :details, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index #all the tasks
    @tasks = Task.all
  end

  def show
    # raise
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    # raise
    @task = Task.new(task_params)
    @task.save
    redirect_to show_task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to show_task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for @task do |f| %>
  <%= f.label :title  %>
  <%= f.text_field :title %>
  <%= f.label :details  %>
  <%= f.text_field :details %>
  <%= f.label :completed  %>
  <%= f.text_field :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>All Tasks</h1>
<%= link_to 'Create new task', tasks_new_path %>
<% @tasks.each do |task| %>
  <h2><%= link_to task.title, show_task_path(task) %> || <%= task.details %> || <%= task.completed %> </h2>
<% end %>

app/views/tasks/new.html.erb
<%= form_for @task do |f| %>
  <%= f.label :title  %>
  <%= f.text_field :title %>
  <%= f.label :details  %>
  <%= f.text_field :details %>
  <%= f.label :completed  %>
  <%= f.text_field :completed %>
  <%= f.submit %>
<% end %>
<!--
# <form action="/tasks" method="post">
#   <%= hidden_field_tag :authenticity_token, form_authenticity_token  %>
#    <label for="title">Title</label>
#    <input type="text" name="task[title]">
#    <label for="details">Details</label>
#    <input type="text" name="task[details]">
#    <label for="completed">Completed</label>
#    <input type="text" name="task[completed]">
#    <input type="submit">
# </form>
#  -->

app/views/tasks/show.html.erb
<h1><%= @task.title %> || <%= @task.details %> || <%= @task.completed %> </h1>
<%= link_to 'back', tasks_path %>
<%= link_to 'edit', task_path(@task) %>
<%= link_to 'delete', destroy_path, method: :delete, data: { confirm: 'Are you sure?'}  %>